FROM node:22

WORKDIR /app

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli@20

# Copia package.json e package-lock.json e instala dependências
COPY package*.json ./
RUN npm install

# Copia todo o código da aplicação
COPY . .

EXPOSE 4200

# Comando para rodar o Angular com hot reload
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
